# Generated by Django 5.2.3 on 2025-07-07 09:27

import django.contrib.auth.validators
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Автор", "verbose_name_plural": "Автори"},
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[
                    core.validators.validate_image_size,
                    core.validators.validate_image_extension,
                ],
                verbose_name="Аватар",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Про себе"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Місто"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Номер телефону"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="specialization",
            field=models.ManyToManyField(
                blank=True,
                related_name="specialists",
                to="projects.category",
                verbose_name="Спеціалізація",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram_url",
            field=models.URLField(blank=True, verbose_name="Telegram"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="Username",
            ),
        ),
    ]
