# Generated by Django 5.2.3 on 2025-07-17 07:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar",
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_original",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/originals/",
                validators=[
                    core.validators.validate_image_size,
                    core.validators.validate_image_extension,
                ],
                verbose_name="Оригінал аватара",
            ),
        ),
    ]
