# Generated by Django 5.2.3 on 2025-07-17 08:46

import core.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_avatar_customuser_avatar_original"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar_original",
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[
                    core.validators.validate_image_size,
                    core.validators.validate_image_extension,
                ],
                verbose_name="Аватар",
            ),
        ),
    ]
