# Generated by Django 5.2.3 on 2025-07-08 10:27

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Назва проєкту"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Короткий опис"
                    ),
                ),
                ("description", models.TextField(verbose_name="Повний опис проєкту")),
                ("fundraising_goal", models.TextField(verbose_name="Мета збору")),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цільова сума, грн",
                    ),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("full_price", "100% з продажу"),
                            ("percentage", "Відсоток від продажу"),
                        ],
                        max_length=20,
                        verbose_name="Тип збору",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Вкажіть, якщо тип збору '100% з продажу'",
                        max_digits=10,
                        null=True,
                        verbose_name="Ціна товару",
                    ),
                ),
                (
                    "donation_percentage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Вкажіть, якщо тип збору '% від продажів'",
                        null=True,
                        verbose_name="Відсоток на донат",
                    ),
                ),
                (
                    "monobank_jar_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        verbose_name="Посилання на МоноБанку",
                    ),
                ),
                (
                    "privatbank_konvert_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        verbose_name="Посилання на Конверт Приватбанку",
                    ),
                ),
                (
                    "paypal_me_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        verbose_name="Посилання на PayPal.Me",
                    ),
                ),
                (
                    "other_payment_details",
                    models.TextField(blank=True, verbose_name="Інші реквізити"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("moderation", "На модерації"),
                            ("active", "Активний"),
                            ("archived", "Архівний"),
                            ("draft", "Чернетка"),
                        ],
                        default="moderation",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершення збору"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кількість переглядів"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.category",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проєкт",
                "verbose_name_plural": "Проєкти",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="project_gallery/",
                        validators=[
                            core.validators.validate_image_size,
                            core.validators.validate_image_extension,
                        ],
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                        verbose_name="Проєкт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення проєкту",
                "verbose_name_plural": "Зображення проєктів",
                "ordering": ["order"],
            },
        ),
    ]
