# Generated by Django 5.2.3 on 2025-07-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_projectimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="donation_percentage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Вкажіть, якщо тип збору '% від продажів'",
                null=True,
                verbose_name="Відсоток на донат, %",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Вкажіть, якщо тип збору '100% з продажу'",
                max_digits=10,
                null=True,
                verbose_name="Ціна товару, грн",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("moderation", "На модерації"),
                    ("active", "Активний"),
                    ("archived", "Архівний"),
                    ("draft", "Чернетка"),
                ],
                default="active",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
