# Generated by Django 5.2.3 on 2025-07-17 07:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_donation_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="image",
        ),
        migrations.AddField(
            model_name="projectimage",
            name="image_original",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_gallery/originals/",
                validators=[
                    core.validators.validate_image_size,
                    core.validators.validate_image_extension,
                ],
                verbose_name="Оригінал зображення",
            ),
        ),
    ]
