# Generated by Django 5.2.3 on 2025-07-17 08:46

import core.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_projectimage_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="image_original",
        ),
        migrations.AddField(
            model_name="projectimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="project_gallery/",
                validators=[
                    core.validators.validate_image_size,
                    core.validators.validate_image_extension,
                ],
                verbose_name="Зображення",
            ),
        ),
    ]
