[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py

# Ігноруємо попередження про застарілі налаштування від dj_rest_auth
filterwarnings =
    ignore:.*app_settings.USERNAME_REQUIRED is deprecated.*:UserWarning
    ignore:.*app_settings.EMAIL_REQUIRED is deprecated.*:UserWarning